#!/usr/bin/env bash
# implement the followings:
#   creatrs a file /var/run/myscript.pid containing the script PID.
#   prints "To infinity and beyond" indefinitely
#   prints "I hate the kill command" upon receiving a SIGTERM
#   prints "Y U no love me?!" upon receiving a SIGINT
#   remove the file /var/run/myscript.pid and kills upon
#+  receiving a SIGQUIT or SIGTERM.

terminator() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && terminator' SIGTERM
  trap 'terminator' SIGQUIT
done
