#!/usr/bin/env bash
# Manage the scripts manage_my_process.
#   When passed the arguments `starts`:
#     1. Start manage_my_process
#     2. Create a file that contains PID in /var/run/my_process.pid
#     3. prints "manage_my_process started"
#   When passed the arguments `stop`:
#     1. Stop manage_my_process
#     2. rm the file /var/run/my_process.pid
#     3. prints "manage_my_process stopped"
#   When passed the arguments `restart`:
#     1. Stop manage_my_process
#     2. rm the file /var/run/my_process.pid
#     3. Start manage_my_process
#     4. Create a file that contain its PID in /var/run/my_process.pid
#     5. prints "manage_my_process restarted"
#   If any other or no arguments is passed, prints
#+  "Usage: manage_my_process {start|stop|restart}"

if [ "${1}" == "start" ]
then
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    echo "manage_my_process stopped"
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
    kill "$(cat /var/run/my_process.pid)"
    rm /var/run/my_process.pid
    ./manage_my_process &
    touch /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
