#!/usr/bin/env bash
# prints num from 1 to 100 for the loops in list format.
#   print "FizzBuzz" when the num is a multiple of 3 and 5.
#   prints "Fizz" when the num is a multiple of 3.
#   prints "Buzz" when the num is a multiple of 5.
#   Otherwise, print the num.

for x in {1..100}
do
  if (( x % 3 == 0 && x % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( x % 3 == 0 ))
  then
    echo "Fizz"
  elif (( x % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$x"
  fi
done
