#!/usr/bin/env bash
# Parses Apache log files in list_format.
#   Groups_visitors by IP and HTTP status code.
#   Prints the num of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
